### ISSUE TITLE
DiscError: cannot open device `/dev/cdrom'

### ISSUE THREAD

**Issue by lnkpaulo** [asartori/mopidy-cd#7] opened 2017-05-24 22:40 UTC
Hi,

I have the following error after the restarting of mopidy in raspberry pi:

```
ERROR [5807:MainThread] mopidy.commands: Got un-handled exception from CdBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 386, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Cd-0.1-py2.7.egg/mopidy_cd/backend.py", line 17, in __init__
    self.cdrom = cdrom.Cdrom()
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Cd-0.1-py2.7.egg/mopidy_cd/cdrom.py", line 14, in __init__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Cd-0.1-py2.7.egg/mopidy_cd/cdrom.py", line 20, in refresh
    self.disc = discid.read()
  File "/usr/local/lib/python2.7/dist-packages/discid/disc.py", line 55, in read
    disc.read(device, features)
  File "/usr/local/lib/python2.7/dist-packages/discid/disc.py", line 152, in read
    raise DiscError(self._get_error_msg())
DiscError: cannot open device `/dev/cdrom'
```
The cdrom is connected. Any idea why this Error?

Btw to install the extension was necessary to do:

```
1. wget http://mirrordirector.raspbian.org/raspbian/pool/main/libd/libdiscid/libdiscid0_0.6.1-6_armhf.deb
2. sudo dpkg -i libdiscid0_0.6.1-6_armhf.deb
3. sudo apt-get install python-dev -y
4. wget http://cddb-py.sourceforge.net/CDDB.tar.gz
5. tar zxvf CDDB.tar.gz && cd CDDB-1.4 && sudo python setup.py install
6. git clone https://github.com/asartori/mopidy-cd
7. cd mopidy-cd && sudo python setup.py install
```
Thanks for support.

**Comment by lnkpaulo** [comment] 2017-05-24 22:52
Hi,

I found the issue, I missed the (_adduser mopidy cdrom_). Now I can see the _cd_ in my Library but unfortunately it is empty, the tracks are not visible :-(.

Any clue?

Thanks.

**Comment by lnkpaulo** [comment] 2017-05-24 23:00
I managed to catch the Error:

```
ERROR [6324:Core-10] mopidy.core.library: CdBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Cd-0.1-py2.7.egg/mopidy_cd/backend.py", line 33, in browse
    for (seq,(number,name,duration)) in enumerate(tracks,1):
ValueError: too many values to unpack
```
But no solution.

Thanks.

**Comment by asartori** [comment] 2017-05-25 06:02
Hi,

sorry, this was a bug caused by a previous merge. It should be fixed now.

**Closed** 2017-05-25 06:02 UTC
